/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Form;

/**
 *
 * @author kanis
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Form form;
    
    public CreateJPanel(Form form) {
        initComponents();
        this.form=form;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcTitle = new javax.swing.JLabel();
        btnName = new javax.swing.JLabel();
        btnState = new javax.swing.JLabel();
        btnDOB = new javax.swing.JLabel();
        btnPhone = new javax.swing.JLabel();
        btnFax = new javax.swing.JLabel();
        btnEmail = new javax.swing.JLabel();
        btnSSN = new javax.swing.JLabel();
        btnMedRec = new javax.swing.JLabel();
        btnHealthPlan = new javax.swing.JLabel();
        btnBankAcc = new javax.swing.JLabel();
        btnLicence = new javax.swing.JLabel();
        btnVehID = new javax.swing.JLabel();
        btnLicencePlate = new javax.swing.JLabel();
        btnDevID = new javax.swing.JLabel();
        btnLinkedIn = new javax.swing.JLabel();
        btnIPA = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedRec = new javax.swing.JTextField();
        txtHealthPlan = new javax.swing.JTextField();
        txtBankAcc = new javax.swing.JTextField();
        txtLicence = new javax.swing.JTextField();
        txtVehID = new javax.swing.JTextField();
        txtLicencePlate = new javax.swing.JTextField();
        txtDevID = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIP1 = new javax.swing.JTextField();
        txtIP2 = new javax.swing.JTextField();
        txtIP3 = new javax.swing.JTextField();
        txtIP4 = new javax.swing.JTextField();
        lstState = new javax.swing.JComboBox<>();

        lblcTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblcTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcTitle.setText("Create Profile");
        lblcTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnName.setText("Name:");

        btnState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnState.setText("State:");

        btnDOB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDOB.setText("Date of Birth:");

        btnPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPhone.setText("Phone:");

        btnFax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFax.setText("Fax:");

        btnEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmail.setText("Email:");

        btnSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSSN.setText("Social Security Number:");

        btnMedRec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMedRec.setText("Medical Record Number:");

        btnHealthPlan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHealthPlan.setText("Health Plan Number");

        btnBankAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBankAcc.setText("Bank Account Number:");

        btnLicence.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLicence.setText("Licence Number:");

        btnVehID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVehID.setText("Vehicle Identification:");

        btnLicencePlate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLicencePlate.setText("Licence Plate");

        btnDevID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDevID.setText("Device Identification:");

        btnLinkedIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLinkedIn.setText("LinkedIn:");

        btnIPA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIPA.setText("Internet Protocol Address:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("jLabel17");

        btnSave.setText("Save");
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtMonth.setText("MM");
        txtMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDay.setText("DD");
        txtDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtYear.setText("YYY");
        txtYear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtFax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtSSN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtMedRec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtHealthPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtBankAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLicence.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtVehID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtLicencePlate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLicencePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicencePlateActionPerformed(evt);
            }
        });

        txtDevID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDevID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevIDActionPerformed(evt);
            }
        });

        txtLinkedIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtIP1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtIP2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtIP3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtIP4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lstState.setModel(new javax.swing.DefaultComboBoxModel(getStates())
        );
        lstState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstStateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHealthPlan)
                            .addComponent(btnBankAcc)
                            .addComponent(btnLicence)
                            .addComponent(btnVehID)
                            .addComponent(btnLicencePlate)
                            .addComponent(btnDevID)
                            .addComponent(btnLinkedIn)
                            .addComponent(btnIPA)
                            .addComponent(jLabel17)
                            .addComponent(btnName)
                            .addComponent(btnState)
                            .addComponent(btnDOB)
                            .addComponent(btnPhone)
                            .addComponent(btnFax)
                            .addComponent(btnEmail)
                            .addComponent(btnSSN)
                            .addComponent(btnMedRec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave)
                                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtPhone)
                            .addComponent(txtFax)
                            .addComponent(txtEmail)
                            .addComponent(txtSSN)
                            .addComponent(txtMedRec)
                            .addComponent(txtName)
                            .addComponent(txtBankAcc)
                            .addComponent(txtHealthPlan)
                            .addComponent(txtLicence)
                            .addComponent(txtVehID)
                            .addComponent(txtLinkedIn)
                            .addComponent(txtDevID)
                            .addComponent(txtLicencePlate)
                            .addComponent(lstState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblcTitle)
                        .addGap(317, 317, 317))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBankAcc, btnDOB, btnDevID, btnEmail, btnFax, btnHealthPlan, btnIPA, btnLicence, btnLicencePlate, btnLinkedIn, btnMedRec, btnName, btnPhone, btnSSN, btnState, btnVehID, jLabel17});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcTitle)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnState)
                            .addComponent(lstState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDOB)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFax)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMedRec)
                            .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHealthPlan)
                            .addComponent(txtHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBankAcc)
                            .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLicence)
                            .addComponent(txtLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVehID)
                            .addComponent(txtVehID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLicencePlate))
                    .addComponent(txtLicencePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevID)
                    .addComponent(txtDevID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIPA)
                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(btnSave)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBankAcc, btnDOB, btnDevID, btnEmail, btnFax, btnHealthPlan, btnIPA, btnLicence, btnLicencePlate, btnLinkedIn, btnMedRec, btnName, btnPhone, btnSSN, btnState, btnVehID, jLabel17});

    }// </editor-fold>//GEN-END:initComponents

    private void txtLicencePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicencePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicencePlateActionPerformed

    private void txtDevIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevIDActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void lstStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstStateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        //final int num_fields=16;
        //int correct_fields=0;
        //String errorMessage="";
        
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    
    private String[] states = {
        "Alabama", "Alaska", "Arizona",
        "Arkansas", "California", "Colorado",
        "Connecticut", "Delaware", "Florida",
        "Georgia", "Hawaii", "Idaho",
        "Illinos", "Indiana", "Lowa",
        "Kansas", "Kentucky", "Louisiana",
        "Maine", "Maryland", "Massachusetts",
        "Michigan", "Minnesota", "Mississipi",
        "Missouri", "Montana", "Nebraska",
        "Nevada", "New Hampshire", "New Jersey",
        "New Mexico", "New York", "North Carolina",
        "North Dakota", "Ohio", "Oklahoma",
        "Oregon", "Penssylvania","Rhode Island",
        "South Carolina", "South Dakota", "Tennesses",
        "Texas", "Utah", "Vermont",
        "Virginia", "Washington", "West Virginia",
        "Wisconsin", "Wyoming"};
    
    public String[] getStates(){
        return states;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBankAcc;
    private javax.swing.JLabel btnDOB;
    private javax.swing.JLabel btnDevID;
    private javax.swing.JLabel btnEmail;
    private javax.swing.JLabel btnFax;
    private javax.swing.JLabel btnHealthPlan;
    private javax.swing.JLabel btnIPA;
    private javax.swing.JLabel btnLicence;
    private javax.swing.JLabel btnLicencePlate;
    private javax.swing.JLabel btnLinkedIn;
    private javax.swing.JLabel btnMedRec;
    private javax.swing.JLabel btnName;
    private javax.swing.JLabel btnPhone;
    private javax.swing.JLabel btnSSN;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnState;
    private javax.swing.JLabel btnVehID;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel lblcTitle;
    private javax.swing.JComboBox<String> lstState;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDevID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthPlan;
    private javax.swing.JTextField txtIP1;
    private javax.swing.JTextField txtIP2;
    private javax.swing.JTextField txtIP3;
    private javax.swing.JTextField txtIP4;
    private javax.swing.JTextField txtLicence;
    private javax.swing.JTextField txtLicencePlate;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedRec;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtVehID;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
