/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Form;

/**
 *
 * @author kanis
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
    }

    ViewJPanel(Form form) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHealthPlan = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtIP4 = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnBankAcc = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnLicence = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        btnVehID = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLicencePlate = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        btnDevID = new javax.swing.JLabel();
        btnLinkedIn = new javax.swing.JLabel();
        txtMedRec = new javax.swing.JTextField();
        txtHealthPlan = new javax.swing.JTextField();
        btnIPA = new javax.swing.JLabel();
        txtBankAcc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLicence = new javax.swing.JTextField();
        lblvTitle = new javax.swing.JLabel();
        txtVehID = new javax.swing.JTextField();
        btnName = new javax.swing.JLabel();
        txtLicencePlate = new javax.swing.JTextField();
        txtDevID = new javax.swing.JTextField();
        btnState = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        btnDOB = new javax.swing.JLabel();
        txtIP1 = new javax.swing.JTextField();
        btnPhone = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnFax = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        btnEmail = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        btnSSN = new javax.swing.JLabel();
        txtIP2 = new javax.swing.JTextField();
        btnMedRec = new javax.swing.JLabel();
        txtIP3 = new javax.swing.JTextField();

        btnHealthPlan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHealthPlan.setText("Health Plan Number");

        txtDay.setText("DD");
        txtDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtIP4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtYear.setText("YYY");
        txtYear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnBankAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBankAcc.setText("Bank Account Number:");

        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnLicence.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLicence.setText("Licence Number:");

        txtFax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnVehID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVehID.setText("Vehicle Identification:");

        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnLicencePlate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLicencePlate.setText("Licence Plate");

        txtSSN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnDevID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDevID.setText("Device Identification:");

        btnLinkedIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLinkedIn.setText("LinkedIn:");

        txtMedRec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtHealthPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnIPA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIPA.setText("Internet Protocol Address:");

        txtBankAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("jLabel17");

        txtLicence.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblvTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblvTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvTitle.setText("View Profile");
        lblvTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtVehID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnName.setText("Name:");

        txtLicencePlate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLicencePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicencePlateActionPerformed(evt);
            }
        });

        txtDevID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDevID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevIDActionPerformed(evt);
            }
        });

        btnState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnState.setText("State:");

        txtLinkedIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        btnDOB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDOB.setText("Date of Birth:");

        txtIP1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPhone.setText("Phone:");

        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnFax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFax.setText("Fax:");

        txtState.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEmail.setText("Email:");

        txtMonth.setText("MM");
        txtMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSSN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSSN.setText("Social Security Number:");

        txtIP2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMedRec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMedRec.setText("Medical Record Number:");

        txtIP3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHealthPlan)
                            .addComponent(btnBankAcc)
                            .addComponent(btnLicence)
                            .addComponent(btnVehID)
                            .addComponent(btnLicencePlate)
                            .addComponent(btnDevID)
                            .addComponent(btnLinkedIn)
                            .addComponent(btnIPA)
                            .addComponent(jLabel17)
                            .addComponent(btnName)
                            .addComponent(btnState)
                            .addComponent(btnDOB)
                            .addComponent(btnPhone)
                            .addComponent(btnFax)
                            .addComponent(btnEmail)
                            .addComponent(btnSSN)
                            .addComponent(btnMedRec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtState)
                            .addComponent(txtPhone)
                            .addComponent(txtFax)
                            .addComponent(txtEmail)
                            .addComponent(txtSSN)
                            .addComponent(txtMedRec)
                            .addComponent(txtName)
                            .addComponent(txtBankAcc)
                            .addComponent(txtHealthPlan)
                            .addComponent(txtLicence)
                            .addComponent(txtVehID)
                            .addComponent(txtLinkedIn)
                            .addComponent(txtDevID)
                            .addComponent(txtLicencePlate))
                        .addGap(18, 18, 18)
                        .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblvTitle)
                        .addGap(317, 317, 317))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvTitle)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnState)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDOB)
                            .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFax)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMedRec)
                            .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHealthPlan)
                            .addComponent(txtHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBankAcc)
                            .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLicence)
                            .addComponent(txtLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVehID)
                            .addComponent(txtVehID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLicencePlate))
                    .addComponent(txtLicencePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevID)
                    .addComponent(txtDevID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIPA)
                    .addComponent(txtIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLicencePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicencePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicencePlateActionPerformed

    private void txtDevIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevIDActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBankAcc;
    private javax.swing.JLabel btnDOB;
    private javax.swing.JLabel btnDevID;
    private javax.swing.JLabel btnEmail;
    private javax.swing.JLabel btnFax;
    private javax.swing.JLabel btnHealthPlan;
    private javax.swing.JLabel btnIPA;
    private javax.swing.JLabel btnLicence;
    private javax.swing.JLabel btnLicencePlate;
    private javax.swing.JLabel btnLinkedIn;
    private javax.swing.JLabel btnMedRec;
    private javax.swing.JLabel btnName;
    private javax.swing.JLabel btnPhone;
    private javax.swing.JLabel btnSSN;
    private javax.swing.JLabel btnState;
    private javax.swing.JLabel btnVehID;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel lblvTitle;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDevID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthPlan;
    private javax.swing.JTextField txtIP1;
    private javax.swing.JTextField txtIP2;
    private javax.swing.JTextField txtIP3;
    private javax.swing.JTextField txtIP4;
    private javax.swing.JTextField txtLicence;
    private javax.swing.JTextField txtLicencePlate;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedRec;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtVehID;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
